---

- name: 'Install required packages'
  package:
    name: '{{ item }}'
    state: latest
  with_items:
  - satellite
  - firewalld
  - python-firewall

- name: 'Ensure firewalld is running'
  service:
    name: firewalld
    state: started
    enabled: yes

- name: 'Open Firewall for Satellite use'
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
  - http
  - https 
  - ssh

