---

- name: "Initialize an empty list for our satellite install params"
  set_fact:
    satellite_install_cmd: ""
    satellite_install_extra_args: ""
    
- name: "Debugging string"
  debug:
    msg: "{{ satellite_deployment_installer_cmd }}"

- name: "Build List of extra args for satellite installation"
  set_fact:
    satellite_install_extra_args: "{{  satellite_install_extra_args }} --{{ item.key }}='{{ item.value }}'"
  with_dict: "{{ satellite_installs_args }}"

- name: "Build List of extra args for satellite installation"
  set_fact:
    satellite_install_cmd: "{{ satellite_deployment_installer_cmd }} {{  satellite_install_extra_args }}"

- name: "Debugging string"
  debug:
    msg: "{{ satellite_install_cmd }}"

- name: "Delete any previous log file"
  file:
    path: "{{ satellite_output_logfile }}"
    state: absent

- name: "Satellite 6 installation"
  command: "{{ satellite_install_cmd }} >>{{ satellite_output_logfile }}"
  register: satinstalloutput


#- name: "Output from installer"
#  debug:
#    msg: "{{ satinstalloutput }}"